/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs245p1;

/**
 *
 * @author Chris
 */
public class ColorGamePanel extends javax.swing.JPanel {
    
    //private javax.swing.JButton jButtonRed;
    //private javax.swing.JButton jButtonYellow;
    //private javax.swing.JButton jButtonGreen;
    //private javax.swing.JButton jButtonBlue;
    //private javax.swing.JButton jButtonPurple;
    
    /**
     * Creates new form ColorGamePanel
     */
    public ColorGamePanel() {
        initComponents();
        //jButtonRed = new javax.swing.JButton();
        //jButtonYellow = new javax.swing.JButton();
        //jButtonGreen = new javax.swing.JButton();
        //jButtonBlue = new javax.swing.JButton();
        //jButtonPurple = new javax.swing.JButton();
    }
    
    public void placeRandomButtons(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clockLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        jButtonRed = new javax.swing.JButton();
        jButtonGreen = new javax.swing.JButton();
        jButtonPurple = new javax.swing.JButton();
        jButtonYellow = new javax.swing.JButton();
        jButtonBlue = new javax.swing.JButton();

        clockLabel.setText("Clock Here");
        clockLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        clockLabel.setPreferredSize(new java.awt.Dimension(150, 25));

        colorLabel.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        colorLabel.setText("Black");

        jButtonRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red button image small transparent.png"))); // NOI18N
        jButtonRed.setToolTipText("");
        jButtonRed.setBorder(null);
        jButtonRed.setBorderPainted(false);
        jButtonRed.setContentAreaFilled(false);

        jButtonGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green button image small transparent.png"))); // NOI18N
        jButtonGreen.setToolTipText("");
        jButtonGreen.setBorder(null);
        jButtonGreen.setBorderPainted(false);
        jButtonGreen.setContentAreaFilled(false);

        jButtonPurple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/purple button image small transparent.png"))); // NOI18N
        jButtonPurple.setToolTipText("");
        jButtonPurple.setBorder(null);
        jButtonPurple.setBorderPainted(false);
        jButtonPurple.setContentAreaFilled(false);

        jButtonYellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yellow button image small transparent.png"))); // NOI18N
        jButtonYellow.setToolTipText("");
        jButtonYellow.setBorder(null);
        jButtonYellow.setBorderPainted(false);
        jButtonYellow.setContentAreaFilled(false);

        jButtonBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue button image small transparent.png"))); // NOI18N
        jButtonBlue.setToolTipText("");
        jButtonBlue.setBorder(null);
        jButtonBlue.setBorderPainted(false);
        jButtonBlue.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorLabel))
                        .addGap(261, 261, 261))))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButtonPurple, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButtonRed, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonPurple, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonRed, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jButtonYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clockLabel;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JButton jButtonBlue;
    private javax.swing.JButton jButtonGreen;
    private javax.swing.JButton jButtonPurple;
    private javax.swing.JButton jButtonRed;
    private javax.swing.JButton jButtonYellow;
    // End of variables declaration//GEN-END:variables
}
