/***************************************************************
* file: CreditsPanel.java
* author: Nicholas Pham
* class: CS 245 – Programming Graphical User Interfaces
*
* assignment: Point and Click Game – v.1.0
* date last modified: 10/05/2017
*
* purpose: This class builds the panel which displays the game credits
*
****************************************************************/
package cs245p1;

import javax.swing.JButton;

/**
 *
 * @author andrewtek
 */
public class CreditsPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreditsPanel
     */
    public CreditsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nickNameLabel = new javax.swing.JLabel();
        creditsLabel = new javax.swing.JLabel();
        andrewNameLabel = new javax.swing.JLabel();
        chrisNameLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(600, 400));

        nickNameLabel.setBackground(java.awt.Color.black);
        nickNameLabel.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        nickNameLabel.setForeground(java.awt.Color.white);
        nickNameLabel.setText("Nicholas Pham");
        nickNameLabel.setToolTipText("creditsNicholas");

        creditsLabel.setBackground(java.awt.Color.black);
        creditsLabel.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        creditsLabel.setForeground(java.awt.Color.white);
        creditsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditsLabel.setText("CREDITS");
        creditsLabel.setToolTipText("creditsTitle");
        creditsLabel.setAlignmentY(0.0F);
        creditsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        andrewNameLabel.setBackground(java.awt.Color.black);
        andrewNameLabel.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        andrewNameLabel.setForeground(java.awt.Color.white);
        andrewNameLabel.setText("Andrew Tek");
        andrewNameLabel.setToolTipText("creditsAndrew");

        chrisNameLabel.setBackground(java.awt.Color.black);
        chrisNameLabel.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        chrisNameLabel.setForeground(java.awt.Color.white);
        chrisNameLabel.setText("Christopher Kilian");
        chrisNameLabel.setToolTipText("creditsChristopher");

        backButton.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        backButton.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(andrewNameLabel)
                    .addComponent(chrisNameLabel)
                    .addComponent(nickNameLabel))
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(creditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chrisNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(andrewNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nickNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBackButton() {
        return backButton;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel andrewNameLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel chrisNameLabel;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JLabel nickNameLabel;
    // End of variables declaration//GEN-END:variables
}
