/***************************************************************
* file: CreditsPanel.java
* author: Nicholas Pham
* class: CS 245 – Programming Graphical User Interfaces
*
* assignment: Point and Click Game – v.1.0
* date last modified: 10/04/2017
*
* purpose: This class defines the panel which displays the game credits
*
****************************************************************/
package cs245p1;

public class CreditsPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreditsPanel
     */
    public CreditsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditsTitle = new javax.swing.JLabel();
        nameAndrew = new javax.swing.JLabel();
        nameChristopher = new javax.swing.JLabel();
        nameNicholas = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(600, 400));

        creditsTitle.setBackground(java.awt.Color.black);
        creditsTitle.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        creditsTitle.setForeground(java.awt.Color.white);
        creditsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditsTitle.setText("CREDITS");
        creditsTitle.setToolTipText("creditsTitle");
        creditsTitle.setAlignmentY(0.0F);
        creditsTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nameAndrew.setBackground(java.awt.Color.black);
        nameAndrew.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        nameAndrew.setForeground(java.awt.Color.white);
        nameAndrew.setText("Andrew Tek");
        nameAndrew.setToolTipText("nameAndrew");

        nameChristopher.setBackground(java.awt.Color.black);
        nameChristopher.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        nameChristopher.setForeground(java.awt.Color.white);
        nameChristopher.setText("Christopher Kilian");
        nameChristopher.setToolTipText("nameChristopher");

        nameNicholas.setBackground(java.awt.Color.black);
        nameNicholas.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        nameNicholas.setForeground(java.awt.Color.white);
        nameNicholas.setText("Nicholas Pham");
        nameNicholas.setToolTipText("nameNicholas");

        backButton.setText("Back");
        backButton.setActionCommand("");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
//Nick
                .addContainerGap(212, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creditsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameAndrew)
                    .addComponent(nameChristopher)
                    .addComponent(nameNicholas))
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
//End Nick
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
//Master
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(creditsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nameChristopher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameAndrew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//Nick
                .addComponent(nameNicholas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
//end nick
                .addComponent(jLabel4)
                .addContainerGap(179, Short.MAX_VALUE))
//master
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Go back to main menu
        
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel creditsTitle;
    private javax.swing.JLabel nameAndrew;
    private javax.swing.JLabel nameChristopher;
    private javax.swing.JLabel nameNicholas;
    // End of variables declaration//GEN-END:variables
}
