/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs245p1;

import java.io.BufferedReader;
import java.io.FileReader;

/**
 *
 * @author minhthuc
 */
public class HighScoresPanel extends javax.swing.JPanel {

//    private BufferedReader br;

    /**
     * Creates new form HighScoresPanel
     */
    public HighScoresPanel() {
        initComponents();
//        String scores = "";
//        try {
//            FileReader fr = new FileReader("highscores.txt");
//            br = new BufferedReader(fr);
//            StringBuilder sb = new StringBuilder();
//            String line = br.readLine();
//            
//            while (line != null) {
//                sb.append(line);
//                line = br.readLine();
//            }
//            scores = sb.toString();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        scoreList.setText(scores);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoresTitle = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        scoreList = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));

        scoresTitle.setBackground(java.awt.Color.black);
        scoresTitle.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        scoresTitle.setForeground(java.awt.Color.white);
        scoresTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoresTitle.setText("HIGH SCORES");
        scoresTitle.setToolTipText("scoresTitle");
        scoresTitle.setAlignmentY(0.0F);
        scoresTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        backButton.setText("Back");
        backButton.setActionCommand("");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        scoreList.setBackground(new java.awt.Color(0, 0, 0));
        scoreList.setToolTipText("scoreList");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        scoreList.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(scoresTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(scoreList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(scoresTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreList, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Go back to main menu

    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane scoreList;
    private javax.swing.JLabel scoresTitle;
    // End of variables declaration//GEN-END:variables
}
