/***************************************************************
* file: MainGamePanel.java
* author: Christopher Kilian
* class: CS 245 – Programming Graphical User Interfaces
*
* assignment: Point and Click Game – v.1.0
* date last modified: 10/04/2017
*
* purpose: This class defines the panel from which the game is actually played
* along with the buttons necessary to do so, as well as the display of the word
* and the hangman.
*
****************************************************************/
package cs245p1;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JButton;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

    
/**
 *
 * @author Chris
 */
public class MainGamePanel extends javax.swing.JPanel {
    /**
     * Creates new form testPanel
     */
    public static List <String> wordsList;
    public static char [] word;
    public static char [] wordGuessed;
    public static String [] gallowPaths = {"../gallows1.jpg", "../gallows2.jpg",
    "../gallows3.jpg", "../gallows4.jpg", "../gallows5.jpg",
    "../gallows6.jpg", "../gallows7.jpg"};
    public static int incorrectGuesses;
  
    //method: MainGamePanel
    //purpose: initialize components get the word and prepare the dashed lines
    // and also set up the clock.    
    public MainGamePanel() {
        initComponents();
        incorrectGuesses = 0;
        word = CS245P1.getGame().getWord().toCharArray();
        wordGuessed = new char [word.length];
        StringBuilder dashLines = new StringBuilder();
        for (int i = 0; i < word.length; i++) {
            wordGuessed[i] = ' ';
            dashLines.append("_" + " ");
        }
        
        jLabelDashedLines.setText(dashLines.toString());
        ActionListener updateClock = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            DateFormat dateFormat = new SimpleDateFormat("MMMM dd,yy hh:mm:ss");
            Date date = new Date();
            clockLabel.setText(dateFormat.format(date).toString());
        }
    };
        Timer timer = new Timer (1000, updateClock);
        timer.setRepeats(true);
        timer.start(); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonM = new javax.swing.JButton();
        jButtonN = new javax.swing.JButton();
        jButtonO = new javax.swing.JButton();
        jButtonP = new javax.swing.JButton();
        jButtonQ = new javax.swing.JButton();
        jButtonR = new javax.swing.JButton();
        jButtonS = new javax.swing.JButton();
        jButtonT = new javax.swing.JButton();
        jButtonU = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jButtonV = new javax.swing.JButton();
        jButtonA = new javax.swing.JButton();
        jButtonW = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jButtonZ = new javax.swing.JButton();
        clockLabel = new javax.swing.JLabel();
        hangmanPanel = new javax.swing.JPanel();
        jLabelGallow = new javax.swing.JLabel();
        skipButton = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();
        jButtonG = new javax.swing.JButton();
        jButtonH = new javax.swing.JButton();
        jButtonI = new javax.swing.JButton();
        jButtonJ = new javax.swing.JButton();
        jButtonK = new javax.swing.JButton();
        jButtonL = new javax.swing.JButton();
        wordPanel = new javax.swing.JPanel();
        jLabelGuessWord = new javax.swing.JLabel();
        jLabelDashedLines = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 400));

        jButtonM.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonM.setText("M");
        jButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMActionPerformed(evt);
            }
        });

        jButtonN.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonN.setText("N");
        jButtonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNActionPerformed(evt);
            }
        });

        jButtonO.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonO.setText("O");
        jButtonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOActionPerformed(evt);
            }
        });

        jButtonP.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonP.setText("P");
        jButtonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPActionPerformed(evt);
            }
        });

        jButtonQ.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonQ.setText("Q");
        jButtonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQActionPerformed(evt);
            }
        });

        jButtonR.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonR.setText("R");
        jButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRActionPerformed(evt);
            }
        });

        jButtonS.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonS.setText("S");
        jButtonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSActionPerformed(evt);
            }
        });

        jButtonT.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonT.setText("T");
        jButtonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTActionPerformed(evt);
            }
        });

        jButtonU.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonU.setText("U");
        jButtonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 51, 51));
        titleLabel.setText("Hangman");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonV.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonV.setText("V");
        jButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVActionPerformed(evt);
            }
        });

        jButtonA.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonA.setText("A");
        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonPush(evt);
            }
        });

        jButtonW.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonW.setText("W");
        jButtonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWActionPerformed(evt);
            }
        });

        jButtonB.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonB.setText("B");
        jButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBActionPerformed(evt);
            }
        });

        jButtonX.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonX.setText("X");
        jButtonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXActionPerformed(evt);
            }
        });

        jButtonC.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonD.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonD.setText("D");
        jButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDActionPerformed(evt);
            }
        });

        jButtonY.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonY.setText("Y");
        jButtonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYActionPerformed(evt);
            }
        });

        jButtonZ.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonZ.setText("Z");
        jButtonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZActionPerformed(evt);
            }
        });

        clockLabel.setText("Clock Here");
        clockLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        clockLabel.setPreferredSize(new java.awt.Dimension(150, 25));

        hangmanPanel.setPreferredSize(new java.awt.Dimension(0, 165));

        jLabelGallow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGallow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallows1.jpg"))); // NOI18N

        javax.swing.GroupLayout hangmanPanelLayout = new javax.swing.GroupLayout(hangmanPanel);
        hangmanPanel.setLayout(hangmanPanelLayout);
        hangmanPanelLayout.setHorizontalGroup(
            hangmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hangmanPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabelGallow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        hangmanPanelLayout.setVerticalGroup(
            hangmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelGallow, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );

        skipButton.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        skipButton.setText("Skip");

        jButtonE.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonE.setText("E");
        jButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEActionPerformed(evt);
            }
        });

        jButtonF.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonF.setText("F");
        jButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFActionPerformed(evt);
            }
        });

        jButtonG.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonG.setText("G");
        jButtonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGActionPerformed(evt);
            }
        });

        jButtonH.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonH.setText("H");
        jButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHActionPerformed(evt);
            }
        });

        jButtonI.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonI.setText("I");
        jButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIActionPerformed(evt);
            }
        });

        jButtonJ.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonJ.setText("J");
        jButtonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJActionPerformed(evt);
            }
        });

        jButtonK.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonK.setText("K");
        jButtonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKActionPerformed(evt);
            }
        });

        jButtonL.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonL.setText("L");
        jButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLActionPerformed(evt);
            }
        });

        jLabelGuessWord.setFont(new java.awt.Font("Century", 0, 36)); // NOI18N
        jLabelGuessWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGuessWord.setText("a b s t r a c t");
        jLabelGuessWord.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelDashedLines.setFont(new java.awt.Font("Century", 0, 36)); // NOI18N
        jLabelDashedLines.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDashedLines.setText("_ _ _ _ _ _ _ _");
        jLabelDashedLines.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout wordPanelLayout = new javax.swing.GroupLayout(wordPanel);
        wordPanel.setLayout(wordPanelLayout);
        wordPanelLayout.setHorizontalGroup(
            wordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wordPanelLayout.createSequentialGroup()
                .addGroup(wordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDashedLines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGuessWord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        wordPanelLayout.setVerticalGroup(
            wordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wordPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelGuessWord, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelDashedLines, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jLabelGuessWord.getAccessibleContext().setAccessibleName("a b s t r a c t ");
        jLabelDashedLines.getAccessibleContext().setAccessibleName("_ _ _ _ _ _ _ _ ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonJ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonK))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonZ)
                                .addGap(142, 142, 142))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonQ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonU)
                                .addGap(21, 21, 21)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(hangmanPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(skipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(wordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skipButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hangmanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonA)
                    .addComponent(jButtonB)
                    .addComponent(jButtonC)
                    .addComponent(jButtonD)
                    .addComponent(jButtonE)
                    .addComponent(jButtonF)
                    .addComponent(jButtonG)
                    .addComponent(jButtonH)
                    .addComponent(jButtonI)
                    .addComponent(jButtonJ)
                    .addComponent(jButtonK))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonN)
                    .addComponent(jButtonO)
                    .addComponent(jButtonP)
                    .addComponent(jButtonQ)
                    .addComponent(jButtonR)
                    .addComponent(jButtonS)
                    .addComponent(jButtonT)
                    .addComponent(jButtonU)
                    .addComponent(jButtonM)
                    .addComponent(jButtonL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonV)
                    .addComponent(jButtonW)
                    .addComponent(jButtonX)
                    .addComponent(jButtonY)
                    .addComponent(jButtonZ))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void aButtonPush(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonPush
        updateGuessedWord('a');
        jButtonA.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_aButtonPush
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBActionPerformed
        updateGuessedWord('b');
        jButtonB.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonBActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        updateGuessedWord('c');
        jButtonC.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonCActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDActionPerformed
        updateGuessedWord('d');
        jButtonD.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonDActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEActionPerformed
        updateGuessedWord('e');
        jButtonE.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());       
    }//GEN-LAST:event_jButtonEActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFActionPerformed
        updateGuessedWord('f');
        jButtonF.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonFActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGActionPerformed
        updateGuessedWord('g');
        jButtonG.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonGActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHActionPerformed
        updateGuessedWord('h');
        jButtonH.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonHActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIActionPerformed
        updateGuessedWord('i');
        jButtonI.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonIActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJActionPerformed
        updateGuessedWord('j');
        jButtonJ.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonJActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKActionPerformed
        updateGuessedWord('k');
        jButtonK.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonKActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLActionPerformed
        updateGuessedWord('l');
        jButtonL.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonLActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMActionPerformed
        updateGuessedWord('m');
        jButtonM.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonMActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNActionPerformed
        updateGuessedWord('n');
        jButtonN.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonNActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOActionPerformed
        updateGuessedWord('o');
        jButtonO.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonOActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPActionPerformed
        updateGuessedWord('p');
        jButtonP.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonPActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQActionPerformed
        updateGuessedWord('q');
        jButtonQ.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonQActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRActionPerformed
        updateGuessedWord('r');
        jButtonR.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonRActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSActionPerformed
        updateGuessedWord('s');
        jButtonS.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonSActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTActionPerformed
        updateGuessedWord('t');
        jButtonT.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonTActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUActionPerformed
        updateGuessedWord('u');
        jButtonU.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonUActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVActionPerformed
        updateGuessedWord('v');
        jButtonV.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonVActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWActionPerformed
        updateGuessedWord('w');
        jButtonW.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonWActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXActionPerformed
        updateGuessedWord('x');
        jButtonX.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonXActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYActionPerformed
        updateGuessedWord('y');
        jButtonY.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonYActionPerformed
    //method: ButtonPush
    //purpose: call update guessedWord and disable the button
    private void jButtonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZActionPerformed
        updateGuessedWord('z');
        jButtonZ.setEnabled(false);
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_jButtonZActionPerformed

    //method: updateGuessedWord
    //purpose: check if the gussed letter is in the word and update the guessed word
    //Will also update the UI    
    public void updateGuessedWord(char letterPushed) {
         List <Integer> index = new ArrayList(CS245P1.getGame().checkLetter(String.valueOf(letterPushed)));
        if (index.isEmpty()) {
            System.out.println("Letter not in word");
            incorrectGuesses++;
            jLabelGallow.setIcon(new javax.swing.ImageIcon(getClass().
                    getResource(gallowPaths[incorrectGuesses]))); 
        }
        else {
            System.out.println(index.size());
            for (int i = 0; i < index.size(); i++) {
                wordGuessed[index.get(i)] = letterPushed;
            }
            updateGuessedWord();
            if (CS245P1.getGame().checkForWin(String.copyValueOf(wordGuessed))) {
                System.out.println("You WIN!");
                //move to game over screen
            }
        }
        System.out.println(CS245P1.getGame().getPoints());
        System.out.println(CS245P1.getGame().getCorrectGuesses());
    }
    //method: getSkipButton
    //purpose: return skip button
    public JButton getSkipButton() {
        return skipButton;
    }
    //method: updateGussedWord
    //purpose: update the UI above the dashed lines
    public void updateGuessedWord() {
        StringBuilder str = new StringBuilder();
        jLabelGuessWord.setFont(new Font("Century 24", Font.PLAIN, 35));
        
        for (int i = 0; i < wordGuessed.length; i++) {
            str.append(wordGuessed[i] + " ");

        }
        jLabelGuessWord.setText(str.toString());
    }

                

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clockLabel;
    private javax.swing.JPanel hangmanPanel;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonG;
    private javax.swing.JButton jButtonH;
    private javax.swing.JButton jButtonI;
    private javax.swing.JButton jButtonJ;
    private javax.swing.JButton jButtonK;
    private javax.swing.JButton jButtonL;
    private javax.swing.JButton jButtonM;
    private javax.swing.JButton jButtonN;
    private javax.swing.JButton jButtonO;
    private javax.swing.JButton jButtonP;
    private javax.swing.JButton jButtonQ;
    private javax.swing.JButton jButtonR;
    private javax.swing.JButton jButtonS;
    private javax.swing.JButton jButtonT;
    private javax.swing.JButton jButtonU;
    private javax.swing.JButton jButtonV;
    private javax.swing.JButton jButtonW;
    private javax.swing.JButton jButtonX;
    private javax.swing.JButton jButtonY;
    private javax.swing.JButton jButtonZ;
    private javax.swing.JLabel jLabelDashedLines;
    private javax.swing.JLabel jLabelGallow;
    private javax.swing.JLabel jLabelGuessWord;
    private javax.swing.JButton skipButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel wordPanel;
    // End of variables declaration//GEN-END:variables
}
