/***************************************************************
* file: MainGamePanel.java
* author: Christopher Kilian
* class: CS 245 – Programming Graphical User Interfaces
*
* assignment: Point and Click Game – v.1.0
* date last modified: 10/04/2017
*
* purpose: This class defines the panel from which the game is actually played
* along with the buttons necessary to do so, as well as the display of the word
* and the hangman.
*
****************************************************************/
package cs245p1;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JButton;

    
/**
 *
 * @author Chris
 */
public class MainGamePanel extends javax.swing.JPanel {
    /**
     * Creates new form testPanel
     */
    public static List <String> wordsList;
    public static char [] word;
    public static char [] wordGuessed;
    
    public MainGamePanel() {
        initComponents();
        word = CS245P1.getGame().getWord().toCharArray();
        wordGuessed = new char [word.length];
        StringBuilder currentWord = new StringBuilder();
        for (int i = 0; i < word.length; i++) {
            wordGuessed[i] = '_';
            currentWord.append(wordGuessed[i] + " ");
        }
        labelWordGuessed.setText(currentWord.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonM = new javax.swing.JButton();
        jButtonN = new javax.swing.JButton();
        jButtonO = new javax.swing.JButton();
        jButtonP = new javax.swing.JButton();
        jButtonQ = new javax.swing.JButton();
        jButtonR = new javax.swing.JButton();
        jButtonS = new javax.swing.JButton();
        jButtonT = new javax.swing.JButton();
        jButtonU = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jButtonV = new javax.swing.JButton();
        jButtonA = new javax.swing.JButton();
        jButtonW = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jButtonZ = new javax.swing.JButton();
        clockLabel = new javax.swing.JLabel();
        hangmanPanel = new javax.swing.JPanel();
        skipButton = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();
        jButtonG = new javax.swing.JButton();
        jButtonH = new javax.swing.JButton();
        jButtonI = new javax.swing.JButton();
        jButtonJ = new javax.swing.JButton();
        jButtonK = new javax.swing.JButton();
        jButtonL = new javax.swing.JButton();
        wordPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelWordGuessed = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 400));

        jButtonM.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonM.setText("M");

        jButtonN.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonN.setText("N");

        jButtonO.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonO.setText("O");

        jButtonP.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonP.setText("P");

        jButtonQ.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonQ.setText("Q");

        jButtonR.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonR.setText("R");

        jButtonS.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonS.setText("S");

        jButtonT.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonT.setText("T");

        jButtonU.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonU.setText("U");

        titleLabel.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 51, 51));
        titleLabel.setText("Hangman");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonV.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonV.setText("V");

        jButtonA.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonA.setText("A");
        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonPush(evt);
            }
        });

        jButtonW.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonW.setText("W");

        jButtonB.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonB.setText("B");

        jButtonX.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonX.setText("X");

        jButtonC.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonC.setText("C");

        jButtonD.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonD.setText("D");

        jButtonY.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonY.setText("Y");

        jButtonZ.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonZ.setText("Z");

        clockLabel.setText("Clock Here");
        clockLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        clockLabel.setPreferredSize(new java.awt.Dimension(150, 25));

        hangmanPanel.setPreferredSize(new java.awt.Dimension(0, 165));

        javax.swing.GroupLayout hangmanPanelLayout = new javax.swing.GroupLayout(hangmanPanel);
        hangmanPanel.setLayout(hangmanPanelLayout);
        hangmanPanelLayout.setHorizontalGroup(
            hangmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hangmanPanelLayout.setVerticalGroup(
            hangmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        skipButton.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        skipButton.setText("Skip");

        jButtonE.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonE.setText("E");

        jButtonF.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonF.setText("F");

        jButtonG.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonG.setText("G");

        jButtonH.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonH.setText("H");

        jButtonI.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonI.setText("I");

        jButtonJ.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonJ.setText("J");

        jButtonK.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonK.setText("K");

        jButtonL.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButtonL.setText("L");

        labelWordGuessed.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        labelWordGuessed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWordGuessed.setText("labelWordGuessed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWordGuessed, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWordGuessed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout wordPanelLayout = new javax.swing.GroupLayout(wordPanel);
        wordPanel.setLayout(wordPanelLayout);
        wordPanelLayout.setHorizontalGroup(
            wordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        wordPanelLayout.setVerticalGroup(
            wordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonJ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonK))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonZ)
                                .addGap(142, 142, 142))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonQ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonU)
                                .addGap(21, 21, 21)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(hangmanPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(skipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(wordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skipButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hangmanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonA)
                    .addComponent(jButtonB)
                    .addComponent(jButtonC)
                    .addComponent(jButtonD)
                    .addComponent(jButtonE)
                    .addComponent(jButtonF)
                    .addComponent(jButtonG)
                    .addComponent(jButtonH)
                    .addComponent(jButtonI)
                    .addComponent(jButtonJ)
                    .addComponent(jButtonK))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonN)
                    .addComponent(jButtonO)
                    .addComponent(jButtonP)
                    .addComponent(jButtonQ)
                    .addComponent(jButtonR)
                    .addComponent(jButtonS)
                    .addComponent(jButtonT)
                    .addComponent(jButtonU)
                    .addComponent(jButtonM)
                    .addComponent(jButtonL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonV)
                    .addComponent(jButtonW)
                    .addComponent(jButtonX)
                    .addComponent(jButtonY)
                    .addComponent(jButtonZ))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aButtonPush(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonPush
        CS245P1.getGame().checkLetter("a");
        System.out.println(CS245P1.getGame().getPoints());
    }//GEN-LAST:event_aButtonPush


    public JButton getSkipButton() {
        return skipButton;
    }
    public void updateDashedLines() {
        StringBuilder str = new StringBuilder();
        for (int i = 0; i < wordGuessed.length; i++) {
            str.append(wordGuessed[i] + " ");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clockLabel;
    private javax.swing.JPanel hangmanPanel;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonG;
    private javax.swing.JButton jButtonH;
    private javax.swing.JButton jButtonI;
    private javax.swing.JButton jButtonJ;
    private javax.swing.JButton jButtonK;
    private javax.swing.JButton jButtonL;
    private javax.swing.JButton jButtonM;
    private javax.swing.JButton jButtonN;
    private javax.swing.JButton jButtonO;
    private javax.swing.JButton jButtonP;
    private javax.swing.JButton jButtonQ;
    private javax.swing.JButton jButtonR;
    private javax.swing.JButton jButtonS;
    private javax.swing.JButton jButtonT;
    private javax.swing.JButton jButtonU;
    private javax.swing.JButton jButtonV;
    private javax.swing.JButton jButtonW;
    private javax.swing.JButton jButtonX;
    private javax.swing.JButton jButtonY;
    private javax.swing.JButton jButtonZ;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelWordGuessed;
    private javax.swing.JButton skipButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel wordPanel;
    // End of variables declaration//GEN-END:variables
}
