/***************************************************************
* file: MenuPanel.java
* author: Andrew Tek
* class: CS 245 – Programming Graphical User Interfaces
*
* assignment: Point and Click Game – v.1.0
* date last modified: 10/04/2017
*
* purpose: This class defines the main menu panel, from which the player can access
* various game features (like the game itself, credits, etc)
*
****************************************************************/
package cs245p1;

import javax.swing.JButton;

/**
 *
 * @author Chris
 */
public class MenuPanel extends javax.swing.JPanel {

    //method: Constructor
    //purpose: Set up panel and shows logo
    public MenuPanel() {
        initComponents();
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().
                    getResource("../trogdor.png"))); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //Auto generated code
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playButton = new javax.swing.JButton();
        highscoreButton = new javax.swing.JButton();
        creditsButton = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        playButton.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        playButton.setText("Play");

        highscoreButton.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        highscoreButton.setText("Highscores");

        creditsButton.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        creditsButton.setText("Credits");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(454, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(creditsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(highscoreButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(playButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(highscoreButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditsButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    //method: getCreditsButton
    //purpose: Returns creditsButton
    public JButton getCreditsButton() {
        return creditsButton;
    }
    //method: getHighButton
    //purpose: Returns highscoreButton
    public JButton getHighscoreButton() {
        return highscoreButton;
    }
    //method: getPlayButton
    //purpose: Returns playButton
    public JButton getPlayButton() {
        return playButton;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creditsButton;
    private javax.swing.JButton highscoreButton;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
