/***************************************************************
* file: PopupCredits.java
* author: Christopher Kilian
* class: CS 245 – Programming Graphical User Interfaces
*
* assignment: Point and Click Game – v.1.2
* date last modified: 10/30/2017
*
* purpose: Defines the popup credits frame which appears when the user
* presses the "F1" key any time in the game
*
****************************************************************/
package cs245p1;

public class PopupCredits extends javax.swing.JFrame {

    //Please note: Auto-generated instance variables are automatically placed at the end of the class definition and cannot be moved
    
    //method: PopupCredits (Constructor)
    //purpose: Set up the frame
    public PopupCredits() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chrisNameLabel = new javax.swing.JLabel();
        andrewNameLabel = new javax.swing.JLabel();
        nickNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.green);
        jLabel1.setText("Point and Click Project ");
        jLabel1.setToolTipText("Project name");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("For team CAN Do");
        jLabel2.setToolTipText("That's us!");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.cyan);
        jLabel3.setText("Fall 2017");
        jLabel3.setToolTipText("School term");

        chrisNameLabel.setBackground(java.awt.Color.lightGray);
        chrisNameLabel.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        chrisNameLabel.setForeground(java.awt.Color.black);
        chrisNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chrisNameLabel.setText("Christopher Kilian, Bronco #012122383");
        chrisNameLabel.setToolTipText("Trogdor was my idea");

        andrewNameLabel.setBackground(java.awt.Color.lightGray);
        andrewNameLabel.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        andrewNameLabel.setForeground(java.awt.Color.black);
        andrewNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        andrewNameLabel.setText("Andrew Tek, Bronco #009604621");
        andrewNameLabel.setToolTipText("Monkey in the middle!!!");

        nickNameLabel.setBackground(java.awt.Color.lightGray);
        nickNameLabel.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        nickNameLabel.setForeground(java.awt.Color.black);
        nickNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nickNameLabel.setText("Nicholas Pham, Bronco #010186410");
        nickNameLabel.setToolTipText("What Up Pham!?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chrisNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(andrewNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nickNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(chrisNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(andrewNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nickNameLabel)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel andrewNameLabel;
    private javax.swing.JLabel chrisNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nickNameLabel;
    // End of variables declaration//GEN-END:variables
}
